This files creates the training and test datasets for all other notebooks and scripts to reuse. This is the file I would typically use for an exploratory analysis.

In [10]:
%run "/code/source/notebooks/notebook_settings.py"
import os
import pandas as pd
from helpsk.utility import Timer
from helpsk.pandas import numeric_summary, non_numeric_summary
from source.service.datasets import DATA

# Data

In [11]:
with Timer("Loading Data"):
    credit = DATA.credit.load()

2023-04-07 04:28:43 - INFO     | Loading data `credit` from `data/processed/credit.pkl`

Timer Started: Loading Data
Timer Finished (0.01 seconds)

In [12]:
numeric_summary(credit)

In [13]:
non_numeric_summary(credit)

---